name: Build All LaTeX Files with "main" in Name

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-latex-recommended texlive-fonts-recommended texlive-science

      - name: Find and Compile LaTeX Files
        run: |
          echo "Searching for main*.tex files..."
          find . -type f -iname "*main*.tex"

          for texfile in $(find . -type f -iname "*main*.tex"); do
            echo "Compiling: $texfile"
            dir=$(dirname "$texfile")
            base=$(basename "$texfile" .tex)
            cd "$dir"

            xelatex -interaction=nonstopmode "$base.tex"
            xelatex -interaction=nonstopmode "$base.tex"

            cd -  # go back to root
          done

      - name: Upload PDFs
        run: |
          for pdf in $(find . -type f -iname "*main*.pdf"); do
            echo "Uploading: $pdf"
            base=$(basename "$pdf" .pdf)
            dir=$(dirname "$pdf")

            gh_output_name="${dir//[\/]/_}_${base}"
            echo "::notice::Creating artifact: $gh_output_name"

            mkdir -p temp_upload
            cp "$pdf" "temp_upload/$gh_output_name.pdf"

          done

      - name: Push Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-main-pdfs
          path: temp_upload/
