name: Build All LaTeX Files with "main" in Name

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-xetex \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-science \
            texlive-bibtex-extra

      - name: Find and Compile LaTeX Files
        run: |
          echo "Searching for '*main*.tex' files..."
          find . -type f -iname "*main*.tex"

          for texfile in $(find . -type f -iname "*main*.tex"); do
            echo "::group::Compiling $texfile"
            dir=$(dirname "$texfile")
            base=$(basename "$texfile" .tex)
            cd "$dir"

            xelatex -interaction=nonstopmode "$base.tex" || true
            xelatex -interaction=nonstopmode "$base.tex" || true

            echo "LaTeX log errors for $base:"
            grep -A 5 "!" "$base.log" || echo "No LaTeX errors detected."

            cd -
            echo "::endgroup::"
          done

      - name: Collect PDFs
        run: |
          mkdir -p temp_upload
          for pdf in $(find . -type f -iname "*main*.pdf"); do
            dir=$(dirname "$pdf")
            base=$(basename "$pdf" .pdf)
            artifact_name="${dir//[^a-zA-Z0-9]/_}_${base}"
            echo "Copying $pdf to temp_upload/${artifact_name}.pdf"
            cp "$pdf" "temp_upload/${artifact_name}.pdf"
          done

      - name: Upload All PDFs
        uses: actions/upload-artifact@v4
        with:
          name: all-main-pdfs
          path: temp_upload/
